CC=g++
#CFLAGS=-g -I/usr/local/include -lallegro_ttf -lallegro_font -lallegro_image -lallegro_primitives -L/usr/local/lib -lallegro
CFLAGS=-g# -I/usr/local/include -lallegro_ttf -lallegro_font -lallegro_image -lallegro_primitives -L/usr/local/lib -lallegro
SOURCE=main.cpp map.cpp cu.cpp a_star.cpp

all:
	$(CC) $(SOURCE) $(CFLAGS) -o magic
